<?php

namespace Database\Factories;

use App\Models\Setting;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Carbon;

class SettingFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Setting::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'name' => 'Nông sản sạch',
            'phone' => '0348520202',
            'email' => 'nongsansach@gmail.com',
            'address' => '55 Giải Phóng - P.Đồng Tâm - Q.Hai Bà Trưng - HN',
            'map' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.7176305540593!2d105.83991261501885!3d21.003953086011823!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ac775d1a29b1%3A0x47ca351d075745a6!2zNTUgR2nhuqNpIFBow7NuZywgxJDhu5NuZyBUw6JtLCDEkOG7kW5nIMSQYSwgSMOgIE7hu5lpLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1608801661186!5m2!1svi!2s',
            'time_work' => 'T2 - CN, 9:00 - 18:00',
            'fanpage' => 'https://www.facebook.com/N%C3%B4ng-s%E1%BA%A3n-s%E1%BA%A1ch-113649023651172',
            'slogan' => 'Chúng tôi chuyên cung cấp các sản phẩm thực phẩm sạch an toàn cho sức khỏe con người',
            'created_at' => Carbon::now(),
            'about_us' => 'Chúng tôi hi vọng tất cả người tiêu dùng Việt nam sẽ được sử dụng những thụ phẩm rau củ quả tươi ngon, bổ dưỡng và an toàn nhất tại cửa hàng cung cấp thực phẩm rau củ sạch Nông Sản Sạch.

Với sứ mệnh trở thành một trong những nhà cung cấp thực phẩm sạch hàng đầu tại Việt Nam đưa đến người tiêu dùng loại nông sản tươi ngon nhất của các vùng miền trên toàn quốc với mục đích là “Mang thiên nhiên về với căn nhà của bạn”.

Với quy trình lựa chọn và kiểm soát nghiêm ngặt Nông Sản Sạch đã tạo nên quỹ đầu tư chuyên thu mua và cung cấp phân phối những sản phẩm rau sạch tươi ngon nhất từ các nông trại phân phối đến tay người tiêu dùng giúp họ có những bữa ăn tươi ngon nhất trong từng sản phẩm khác biệt từ thiên nhiên.

Công Ty Cổ Phần Phát Triển Dũng Hà chuyên cung cấp thực phẩm sạch, được trồng và chăm sóc theo quy trình từ các nông trại trên toàn quốc đưa đến tận tay người tiêu dùng. Hệ thống phân phối của chúng tôi đã được đăng ký và sở hữu là www.nongsandungha.com và có địa chỉ tại: A11 ngõ 100 đường Trung Kính quận Cầu Giấy Tp. Hà Nội.

Video Hành trình phát triển 5 năm của Nông Sản Sạch Với triết lý trong kinh doanh là tuân thủ và đảm bảo được chất lượng tươi ngon nhất, nguồn gốc xuất xứ về sản phẩm rõ ràng.Chúng tôi cam kết không sử dụng chất bảo quản nào bị Bộ Y Tế cấm không được sử dụng và cam kết với quý khách hàng về toàn bộ những sản phẩm được phân phối qua hệ thống phân phối Nông Sản Sạch đảm bảo an toàn nhất. Với cam kết chỉ phân phối những hàng hóa được cung cấp từ những nhà sản xuất có uy tín và đã được cơ quan y tế có thẩm quyền cấp chứng nhận và đảm bảo vệ sinh an toàn thực phẩm có đủ quyền cung cấp thực phẩm sạch, các loại nông sản là các đặc sản từ mọi miền trên toàn quốc, các thực phẩm sử dụng hàng ngày như thủy hải sản tươi sống, đồ đông lạnh (cá, tôm, cua,...) thịt tươi sống (thịt bò, thịt lợn, thịt gà,..); các thực phẩm được đóng gói, thực phẩm được chế biến sẵn, rau củ quả, các loại gạo vùng miền và các loại phụ gia về thực phẩm như các loại gia vị dùng trong việc chế biến món ăn hàng ngày,...

Với những nhu cầu trong và ngoài nước Nông Sản Sạch luôn đáp ứng được yêu cầu khắt khe nhất của quý vị. Chúng tôi cung cấp thực phẩm sạch cho các đơn vị: khách sạn, nhà hàng, các bếp ăn công nghiệp, các trường học, trường mầm non, các hệ thông giáo dục là các cửa hàng, các chợ đầu mối và đặc biệt là xuất bán sang nước bạn như Đài Loan, Trung Quốc, Nga, Séc,... Dưới đây, chúng tôi xin điểm qua những mặt hàng của Nông Sản Sạch hiện đang được rất nhiều khách hàng tin dùng và ưa chuộng: Rau củ sạch Đà Lạt, an toàn có nguồn gốc rõ ràng Với những loại rau củ là những loại đặc sản tại các vùng miền Nông Sản Sạch là địa chỉ uy tín cung cấp cho bạn các loại sản phẩm chất lượng từ các loại rau củ sạch Đà Lạt được nhiều người dân ủng hộ trong suốt khoảng thời gian qua.Hệ thống vận hành của chúng tôi được thực hiện theo dây chuyền đảm bảo rằng các bạn sẽ nhận được thực phẩm tươi nhất với thời gian vận chuyển ngắn nhất đáp ứng được độ tươi ngon đảm bảo vệ sinh, an toàn và ngon miệng. Có rất nhiều loại rau thuộc đặc sản tại Đà Lạt như : Rau rocket thường được làm các món salad hấp dẫn ăn kèm với các loại rau mầm cải, các loại rau xà lách Đà Lạt, bí nụ là thực phẩm được hái trực tiếp từ Nông Sản Sạch, Đậu Hà Lan và rất rất nhiều những thực phẩm khác tại Đà Lạt. Đặc sản Hà Giang Những đặc sản Hà Giang ngày càng được săn lùng nhiều tại Hà Nội bởi trong từng loại thực phẩm có chứa nhiều giá trị dinh dưỡng có lợi cho sức khỏe con người. Để đáp ứng được mong đợi của quý bạn Nông Sản Sạch cũng đã bắt tay với những hộ nông dân tại Hà Giang phân phối đến quý vị và các bạn những sản phẩm có nguồn gốc rõ ràng nhất và chất lượng nhất. Nhiều loại đặc sản Hà Giang được khách hàng yêu thích như : Mật ong hoa bạc hà được lấy tại cao nguyên đá Đồng Văn hàng năm chỉ được lấy một lần nên là loại thực phẩm rất tốt cho sức khỏe, hoa tam thất khô là loại thảo dược chuyên trị mất ngủ, hoa atiso khô thanh nhiệt mát gan, các loại gia vị mang đậm tính chất Tây Bắc hạt dổi, gia vị mắc khén, các loại hạt dinh dưỡng, đồ ngâm rượu ngon,.... Đặc Sản Vùng Miền Được mua từ các vùng miền khác nhau trên nhiều tỉnh thành trên cả nước (Bến Tre, Gia Lai, Đăk Lăk, Điện Biên, Hòa Bình, Hà Giang,…) được phân phối tại coác cơ sở của công ty tại Hà Nội.Chúng tôi luôn đảm bảo được chất lượng tốt nhất đến tay người tiêu dùng không vì rào cản địa lý. Để làm được điều này chúng tôi luôn có những quy trình làm việc phối hợp với nhau từ lúc thu mua đến việc vận chuyển các sản phẩm nhanh chóng và tiết kiệm nhất do vậy quý khách có thể sử dụng sản phẩm tươi ngon nhất mà không lo về giá thành sản phẩm. đặc sản vùng miền Một số những sản phẩm nổi bật:

Măng Tây Đây là một trong những sản phẩm mũi nhọn của Nông Sản Sạch. Chúng tôi nhập khẩu giống măng Tây từ Mỹ phân phối cho bà con gieo trồng với kỹ thuật và chăm sóc nghiêm ngặt. Thu mua trực tiếp để đảm bảo chất lượng măng tây cung cấp cũng như giá thành sản phẩm. Là một trong những sản phẩm được phân phối chủ yếu tại Nông Sản Sạch. Với hạt giống được nhập khẩu từ Mỹ và phân phối cho bà con vùng miền gieo trông với những kỹ thuật và quy trình làm việc được thực hiện nghiêm ngặt. Việc thu mua được thực hiện trực tiếp ngay tại nông trại để đảm bảo giá thành cũng như sản phẩm được tươi và tiết kiệm nhất. Hiện nay chúng tôi đang phân phối sản phẩm măng tây cho các nhà hàng, đại lý và nhận được sự ủng hộ từ nhiều đơn vị về sản phẩm mà chúng tôi cung cấp. các mon ngon từ măng tây Củ Hũ Dừa –Một đặc sản mang đậm văn hóa Bến Tre Đây là thành phần được hái trên đọt cây dừa cũng là phần được xem là ngon nhất của cây được chế biến thành những món ăn dẫn dã, mang đậm màu sắc Bến Tre gây thương nhớ cho bao thực khách đã có cơ hội đến và thưởng thức chúng. Không những thế nào còn được sử dụng để chế biến thành nhiều món ăn khác nhau như xào lòng ga, chiên bánh xèo, xào tôm, bóp xổi, mấu tôm thịt, chế biến các món canh thịt viên nấu hay chỉ đơn giản là sử dụng tươi. Lựa chọn một củ hủ dừa tươi ngon không khó vì hiện giờ nó đã được phân phối tại Nông Sản Sạch được nhập khẩu trực tiếp tại Bến Tre đảm bảo chất lượng tốt nhất đến với khách hàng. Mầm Đá Là đặc sản tại vùng đất Sapa, rau mầm đá được khách hàng cực kỳ yêu thích vì nó rất ít khi được bán. Đặc điểm của cây này sinh sống tại các vùng đá cao và sinh trưởng mạnh ở mùa lạnh từ tháng 9 đến tháng 2 hàng năm âm lịch.

Nhưng đáp ứng nhu cầu của quý khách hàng tại cơ sở Nông Sản Sạch cũng đảm bảo được cung cấp đặc sản hấp dẫn từ vùng này đến với khách hàng. Rau Bò Khai Có nhiều tên gọi để chỉ loại rau này như rau bồ khai, rau khau hương, rau phắc hiển, rau hiến,...Nó được phát triển tự nhiên tại vùng đá Hà Giang, Tuyên Quang, Lạng Sơn, Cao Bằng,...ở ven các bìa rừng hay vùng núi đá hiểm trở. Cũng là những đặc sản tại các vùng đất trên như các nông sản mang tính đặc sản như: Ngó Xuân, Rau Rừng Gia Lai, Rau lủi, Rau Đắng, Lá Giang,... cũng được phân phối tại Nông Sản Sạch. Thực phẩm luôn đảm bảo độ tươi ngon nhất và các quy chuẩn về vệ sinh an toàn thực phẩm với giá cả phù hợp với túi tiền của bạn bao gồm nhiều loại thực phẩm được sử dụng hàng ngày như các thực phẩm rau ăn lá: rau muống, các loại cải, bắp cải, rau ngót, …. Các loại củ quả: các loại khoai tây, khoai lang, khoai môn, bầu, bí, cà chua,… rau củ sạch Thực phẩm tươi sống: Thịt các loại: Thịt mông sấn,Dẻ sường bò, thịt bắp, Đùi Gà, Gà ta, Dẻ sườn bỏ, Thịt ba chỉ cả tấm,... Thủy hải sản: Các loại thủy hải sản đa dạng Cá Diêu Hồng, Cá basa, Cá Chim,… hải sản Các loại đồ khô, phụ gia thực phẩm (gia vị an toàn): các loại gạo, dầu ăn, hạt nêm, bột phụ gia,… Nông Sản Sạch chuyên cung cấp thực phẩm sạch tại Hà Nội Cung cấp thực phẩm sạch cho nhà hàng, quán ăn Chúng tôi tự hào là đơn vị chuyên cung cấp thực phẩm sạch tại Hà Nội uy tín đáp ứng cho nhiều nhà hàng lớn nhỏ trên địa bàn cả nước như: Nhà hàng Aquaria, nhà hàng Hương Sen, Nguyên Đình catering,... Tất cả các loại rau rừng mang đậm màu sắc các vùng miền, gia vị và những hương liệu từ phổ biến đến những loại gia vị hạn chế ít được bày bán trên thị trường thị tại Dũng Hà bạn cũng có thể tìm thấy những sản phẩm này. Nhiều thực phẩm được nhiều quý khách hàng cực kỳ yêu thích như: ngồng tỏi, ngó xuân, rau tiến vua, rau lủi,... Đồng thời, các gia vị mang đậm hương vị của các nhà hàng, món ăn. Nông Sản Sạch cung cấp hương liệu tự nhiên và gia vị bếp ăn nhà hàng gồm có: Lá Thyme (xạ hương), lá hương thảo, mắc kén, hạt tiêu,...Các thực phẩm tươi sống được cung cấp hàng ngày tại các quán ăn đảm bảo chất lượng tươi 100% đạt tiêu chuẩn về vệ sinh và an toàn thực phẩm tươi ngon nhất.

Cung cấp thực phẩm sạch cho siêu thị Tại các siêu thị trên địa bàn thành phố Hà Nội và trên địa bàn tỉnh, các nhà phân phối thực phẩm sạch trên phạm vi cả nước hiện đang là đối tác phân phối chính của thực phẩm Nông Sản Sạch.Là đối tác lớn của các siêu thị như Vinmart, siêu thị Co-op mart, siêu thị Big C,... tất cả các sản phẩm đều đủ tiêu chuẩn kiểm định cung cấp thực phẩm sạch tại các trung tâm siêu thị lớn. Các sản phẩm được yêu thích nhất là các loại rau rừng, rau đặc sản, hoa quả tươi, hoa quả nhập khẩu...Cụ thể như: Cà rốt baby, các loại rau xà lách Đà Lạt, đặc sản rau ngó xuân, hạt tiêu xanh Đắc Lắc,.... dưa leo, rau củ theo mùa thực phẩm cho siêu thị Cung cấp thực phẩm sạch cho bếp ăn trường học Đảm bảo sức khỏe học đường hiện nay Nông Sản Sạch ký kết đảm bảo việc cung cấp thực phẩm sạch cho các bếp ăn tại các trường học.Nông Sản Sạch cam kết tất cả các thực phẩm đều đạt tiêu chuẩn về vệ sinh an toàn thực phẩm trước khi được đưa đến nhà bếp của các trường học. Chúng tôi cũng cam kết phân phối các thực phẩm đảm bảo chất lượng tươi ngon, nguồn gốc xuất xứ rõ ràng,... Cung cấp hoa quả sạch cho quán karaoke Ngoài các sản phẩm rau, gia vị, các thực phẩm tươi sống thì tại các quán karaoke Nông Sản Sạch còn chuyên cung cấp các thực phẩm tươi sống, hoa quả cung cấp trái cây cho quán karaoke uy tín. Đa dạng các loại quả thuộc các vùng miền như: Bưởi da xanh, ổi giòn giòn, bưởi năm roi ngọt mát, xoài cát, dưa lưới,...

Ngoài ra còn có nhiều loại hoa quả nhập khẩu gồm Lê Nam Phi, Kiwi, Táo Queen,... Đảm bảo cung cấp hoa quả sạch chất lượng tốt nhất 100% tươi ngon. Mua thực phẩm sạch tại hà nội Rất nhiều bạn sống tại Hà Nội có những câu hỏi băn khoăn như: thực phẩm sạch mua ở đâu? mua thực phẩm sạch ở đâu hà nội ? Các cửa hàng thực phẩm sạch tại Hà Nội, Nông Sản Sạch hiện này với nhiều năm chuyên phân phối trên thị trường hiện nay là một trong những cơ cở phân phối uy tín quý khách hàng có thể lựa chọn trực tiếp tại cửa hàng của Dũng Hà hay trên trang cung cấp thực phẩm sạch online. Chúng tôi hiện nay đã có được lòng tin của những quý khách hàng trên thị trường bán thực phẩm sạch tại Hà Nôi, và trên toàn quốc, do đó được tiếp thêm sức mạnh để tiếp tục con đường cung cấp thực phẩm sạch tới tận tay người tiêu dùng.

Hy vọng trong thời gian tới nhờ sản phẩm uy tín, dịch vụ chuyên nghiệp, sản phẩm của Nông Sản Sạch chúng tôi sẽ được tới tay nhiều khách hàng hơn, không chỉ ở Hà Nội và các tỉnh thành lân cận mà còn hướng tới phân phối rộng khắp toàn quốc.

Với phương châm “Cung Cấp Thực Phẩm Sạch – An Toàn – Dịch Vụ Chuyên Nghiệp” Nông Sản Sạch bảo đảm đáp ứng mọi yêu cầu, nhu cầu của Quý khách thông qua hệ thống cung cấp chuyên nghiệp với giá cả, chất lượng tốt nhất, thời gian giao hàng nhanh nhất và phục vụ tốt nhất tới tận tay Quý khách hàng. Để nâng cao chất lượng sản phẩm và chất lượng phục vụ cung cấp thực phẩm sạch online ở Hà Nội phấn đấu rộng khắp toàn quốc ngày càng tốt hơn, công ty chúng tôi mong được sự ủng hộ và đón nhận ý kiến đóng góp từ phía Quý khách mọi chi tiến xin liên hệ với Nông Sản Sạch để được tư vấn miễn phí.'
        ];
    }
}
